files:
  - source: /PowerEditor/installer/nativeLang/english.xml
    translation: /PowerEditor/installer/nativeLang/%language%.xml
    languages_mapping:
      language:
        af: afrikaans
        sq: albanian
        ar: arabic
        an: aragonese
        az: azerbaijani
        eu: basque
        be: belarusian
        bn: bengali
        bs: bosnian
        br-FR: breton
        bg: bulgarian
        ca: catalan
        zh-CN: chineseSimplified
        zh-TW: chinese
        co: corsican
        hr: croatian
        cs: czech
        da: danish
        nl: dutch
        en: english
        eo: esperanto
        et: estonian
        fi: finnish
        fr: french
        fur-IT: friulian
        gl: galician
        ka: georgian
        de: german
        el: greek
        gu-IN: gujarati
        he: hebrew
        hi: hindi
        hu: hungarian
        id: indonesian
        it: italian
        ja: japanese
        kab: kabyle
        kn: kannada
        kk: kazakh
        ko: korean
        ku: kurdish
        ky: kyrgyz
        lv: latvian
        lij: ligurian
        lt: lithuanian
        lb: luxembourgish
        mk: macedonian
        ms: malay
        mr: marathi
        mn: mongolian
        nb: norwegian
        nn-NO: nynorsk
        oc: occitan
        fa: farsi
        pl: polish
        pt-PT: portuguese
        pt-BR: brazilian_portuguese
        pa-IN: punjabi
        ro: romanian
        ru: russian
        sc: sardinian
        sr: serbianCyrillic
        sr-CS: serbian
        si-LK: sinhala
        sk: slovak
        sl: slovenian
        es-ES: spanish
        es-AR: spanish_ar
        sv-SE: swedish
        tl: tagalog
        tg: tajik
        ta: tamil
        tt-RU: tatar
        te: telugu
        th: thai
        tr: turkish
        uk: ukrainian
        ur-IN: urdu
        ug: uyghur
        uz: uzbek
        vi: vietnamese
        cy: welsh
    content_segmentation: 0
    translatable_elements:
      - '/**/[@name]'
